on:
  push:
    paths:    
    - 'website/geoBoundaries/**'
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
        repository: wmgeolab/gbRelease
        ref: master
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://ftp.geoboundaries.org/geoboundaries.org/
        ftp-username: geologs
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: website/geoBoundaries
        #git-ftp-args: --dry-run

